export const strings = {
  appTitle: "Shardling",
  menu: {
    play: "Play",
    settings: "Settings",
    versionPrefix: "v",
    credits: "Made by Sid Ahmed Sahraoui",
  },
  settings: {
    title: "Settings",
    volume: "Volume",
    mute: "Mute",
    reduceMotion: "Reduce motion",
    camSensitivity: "Camera sensitivity",
    back: "Back",
    on: "On",
    off: "Off",
  },
  hud: {
    shards: "Shards",
    time: "Time",
    deaths: "Deaths",
    pause: "Pause",
  },
  pause: {
    title: "Paused",
    resume: "Resume",
    restart: "Restart level",
    quitToMenu: "Back to menu",
  },
  levelSelect: {
    title: "Levels",
    back: "Back",
    worldPrefix: "World ",
    worldNames: ["Emberfall", "The Gears", "Updraft", "The Hollow Heart"],
    comingSoon: "Coming soon",
    locked: "Locked",
    best: "Best",
    deaths: "Deaths",
  },
  complete: {
    title: "Level complete",
    time: "Time",
    deaths: "Deaths",
    best: "Best",
    newBest: "New best!",
    noBest: "—",
    next: "Next level",
    replay: "Replay",
    levels: "Levels",
  },
  orientation: {
    rotate: "Rotate your device to play",
  },
  touch: {
    move: "Move",
    jump: "Jump",
  },
  debug: {
    panelTitle: "Tuning",
    folderMovement: "Movement",
    folderCamera: "Camera",
    folderPostFx: "PostFX (applies on reload)",
    copyAsCode: "Copy as code",
    hudFps: "fps",
    hudDrawCalls: "draw",
    hudTriangles: "tris",
    hudBodies: "bodies",
    hudGeometries: "geoms",
    hudState: "state",
    hudFreeFly: "fly [F]",
    hudOn: "on",
    hudOff: "off",
    hudNone: "—",
  },
} as const;

export type Strings = typeof strings;
